DROP SCHEMA PUBLIC CASCADE

CREATE MEMORY TABLE INT_PARTS (ID INTEGER NOT NULL PRIMARY KEY, NAME VARCHAR(50), BRAND VARCHAR(50) NOT NULL)

CREATE MEMORY TABLE EXT_PRODUCT (ID INTEGER NOT NULL PRIMARY KEY, NAME VARCHAR(50) NOT NULL, BRAND VARCHAR(50) NOT NULL, CATEGORY VARCHAR(50) NOT NULL, PRICE DECIMAL(10,2) NOT NULL, TAX INTEGER NOT NULL, CREATED_ON TIMESTAMP NOT NULL)
CREATE MEMORY TABLE EXT_PART (ID INTEGER NOT NULL, PRODUCT_ID INTEGER NOT NULL, NAME VARCHAR(50) NOT NULL, BRAND VARCHAR(50) NOT NULL, CONSTRAINT EXT_PART_PK PRIMARY KEY (ID, PRODUCT_ID))


insert into INT_PARTS values (100001, 'SForcable 3320', 'SVidea')
insert into INT_PARTS values (100002, 'BZM E32s F', 'Merkloos')
insert into INT_PARTS values (100003, '1GB PC2700 DDR Elite', 'Bumston')
insert into INT_PARTS values (100004, 'Apacer Compact Flash', 'Insanedisk')
insert into INT_PARTS values (100005, 'FP-IN9 SLI nForce 650i SLI', 'IDME')
insert into INT_PARTS values (100006, 'Haloen 32S3', 'Dropjes')
insert into INT_PARTS values (100007, 'AMC Balton 64 S2 44500', 'AMC')
insert into INT_PARTS values (100008, 'Spinner 32 600W', 'Corset')
insert into INT_PARTS values (100009, 'Windmaker 322 400F', 'Vale-Elec')
